### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by chrisprojs** [StartHua/ComfyUI_Seg_VITON#11]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\stabel_vition.py", line 152, in sample
    z, c = self.model.get_input(batch, params.first_stage_key)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\cldm\cldm.py", line 56, in get_input
    x, c = super().get_input(batch, self.first_stage_key, *args, **kwargs)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\ldm\models\diffusion\ddpm.py", line 803, in get_input
    encoder_posterior = self.encode_first_stage(x)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\ldm\models\diffusion\ddpm.py", line 887, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\ldm\models\autoencoder.py", line 85, in encode
    h = self.encoder(x)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\ldm\modules\diffusionmodules\model.py", line 523, in forward
    hs = [self.conv_in(x)]
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

I got this error when running stable vition

**Comment by SevenAntares** [comment]
same problem
