### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers.models.autoencoder_kl'

### ISSUE THREAD

**Issue by florestefano1975** [StartHua/ComfyUI_Seg_VITON#15]
ERROR: !!! Exception during processing !!!
ERROR: Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Seg_VITON/stabel_vition.py", line 128, in sample
    self.model = create_model(config_path=None, config=config)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Seg_VITON/cldm/model.py", line 8, in create_model
    model = instantiate_from_config(config.model).cpu()
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Seg_VITON/ldm/util.py", line 119, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Seg_VITON/ldm/util.py", line 127, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Seg_VITON/cldm/cldm.py", line 14, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Seg_VITON/ldm/models/diffusion/ddpm.py", line 26, in <module>
    from diffusers.models.autoencoder_kl import AutoencoderKLOutput
ModuleNotFoundError: No module named 'diffusers.models.autoencoder_kl'

**Comment by shisheng660** [comment]
File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_Seg_VITON\cldm\cldm.py", line 14, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_Seg_VITON\ldm\models\diffusion\ddpm.py", line 26, in <module>
    from diffusers.models.autoencoder_kl import AutoencoderKLOutput
ModuleNotFoundError: No module named 'diffusers.models.autoencoder_kl'

Prompt executed in 14.16 seconds

I got the same error. How did you fix it, Thanks!

**Comment by florestefano1975** [comment]
> File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_Seg_VITON\cldm\cldm.py", line 14, in from ldm.models.diffusion.ddpm import LatentDiffusion File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_Seg_VITON\ldm\models\diffusion\ddpm.py", line 26, in from diffusers.models.autoencoder_kl import AutoencoderKLOutput ModuleNotFoundError: No module named 'diffusers.models.autoencoder_kl'
> 
> Prompt executed in 14.16 seconds
> 
> I got the same error. How did you fix it, Thanks!

I have updated ComfyUI and several nodes. However I encountered further errors and am still looking for a solution.

**Comment by whmc76** [comment]
anyone fix this ?

**Comment by shisheng660** [comment]
> > File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_Seg_VITON\cldm\cldm.py", line 14, in from ldm.models.diffusion.ddpm import LatentDiffusion File "E:\ComfyUI-aki-v1.1\custom_nodes\ComfyUI_Seg_VITON\ldm\models\diffusion\ddpm.py", line 26, in from diffusers.models.autoencoder_kl import AutoencoderKLOutput ModuleNotFoundError: No module named 'diffusers.models.autoencoder_kl'
> > Prompt executed in 14.16 seconds
> > I got the same error. How did you fix it, Thanks!
> 
> I have updated ComfyUI and several nodes. However I encountered further errors and am still looking for a solution.

I may have solved this problem, but I'm encountering new ones

This my solution:
Open custom_nodes\ComfyUI_Seg_VITON\ldm\models\diffusion\ddpm.py
Code:
"""
from diffusers.models.autoencoder_kl import AutoencoderKLOutput
from diffusers.models.vae import DecoderOutput
"""
to
"""
from diffusers.models.autoencoders.autoencoder_kl import AutoencoderKLOutput
from diffusers.models.autoencoders.vae import DecoderOutput
"""
This path will change when you move to a new version of the software
