### ISSUE TITLE
When comfyUI starting： ModuleNotFoundError: No module named 'ldm.models.diffusion.sampling_util'

### ISSUE THREAD

**Issue by ultimatech-cn** [StartHua/ComfyUI_Seg_VITON#2]
Traceback (most recent call last):
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\__init__.py", line 32, in <module>
    from .stabel_vition import *
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\stabel_vition.py", line 11, in <module>
    from .cldm.plms_hacked import PLMSSampler
  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\cldm\plms_hacked.py", line 8, in <module>
    from ldm.models.diffusion.sampling_util import norm_thresholding
ModuleNotFoundError: No module named 'ldm.models.diffusion.sampling_util'

Cannot import E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON module for custom nodes: No module named 'ldm.models.diffusion.sampling_util'

Any solution for this？

**Comment by zUoWHhh** [comment]
> 回溯（最近一次调用最后一次）：文件“E：\DEV\ComfyUI_windows_portable\ComfyUI\nodes.py”，第 1893 行，load_custom_node module_spec.loader.exec_module（module） 文件 “”，第 883 行，在 exec_module 文件 “”，第 241 行，在 call_with_frames_removed _ 文件 “E：\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON__init__.py”，第 32 行，从.stabel_vition导入 *文件“E：\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\stabel_vition.py”，第 11 行，从.cldm.plms_hacked导入 PLMSSampler 文件 “E：\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\cldm\plms_hacked.py”，第 8 行，从ldm.models.diffusion.sampling_util导入norm_thresholding ModuleNotFoundError：没有名为“ldm.models.diffusion.sampling_util”的模块
> 
> 无法为自定义节点导入 E：\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON 模块：没有名为“ldm.models.diffusion.sampling_util”的模块
> 
> 有什么解决方案吗？

Have you solved this problem?

**Comment by ultimatech-cn** [comment]
Sure， so far there are three ways as I know
1. update your diffusers to latest
2. idm的问题，是需要把节点目录下的idm文件夹拷贝到site-package下
3. changing the name of idm( not tried)

I used the second method. Good luck.
